### ISSUE TITLE
old documentation link

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#104]
The repo description includes a link to http://collectiveeasyform.readthedocs.org which is out of date. The link there "Edit on GitHub" also points to the Quintagroup repo. Can we remove this link from the repo description or do we want to maintain the readthedocs.org hosting of easyform docs?

**Comment by tkimnguyen** [comment]
If we remove the link, we should also ask that http://collectiveeasyform.readthedocs.org be removed from readthedocs.org

**Comment by jensens** [comment]
link points to pypi now
