### ISSUE TITLE
allow widget selection for a field

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#107]
allow adding of other widgets from z3cform, e.g. equivalent to 
editing the model schema from `<form:widget type="z3c.form.browser.select.CollectionSelectfieldWidget"/>` to `<form:widget type="z3c.form.browser.radio.RadioFieldWidget"/>`

the easyform fields editor needs quick picks for the different widgets, like a drop down select and defining the widgets to allow

**Comment by jensens** [comment]
I think we already have this in the edit form:

![screenshot from 2018-05-07 16 38 51](https://user-images.githubusercontent.com/157140/39707626-387120f8-5215-11e8-96a2-4f2c10480a36.png)

whats missing?

**Comment by rnunez80** [comment]
the choice field does not let you select RadioFieldWidget

**Comment by jensens** [comment]
Well, here it does (latest master at least). what's the versions of plone and addon your using?

**Comment by tomgross** [comment]
I can confirm this works.
