### ISSUE TITLE
can we make a production release?

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#119]
We've been hanging around in beta land for a while now. It works pretty well. Let's do it.

**Comment by tomgross** [comment]
We are using easyform in production quite a while now. Except from encoding issues now and then (https://github.com/collective/collective.easyform/pull/127) it is pretty stable and works well.

**Comment by pbauer** [comment]
Do we want https://github.com/collective/collective.easyform/pull/117 merged before a release?

**Comment by tomgross** [comment]
I merged #117.

**Comment by pbauer** [comment]
Feel free yo make a release!

**Comment by tomgross** [comment]
I would but I don't have permission on pypi.
/cc @jensens @agitator

**Comment by jensens** [comment]
bitteschön https://pypi.org/project/collective.easyform/2.0.0/
