### ISSUE TITLE
add a way to access a form's save data adapters

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#120]
In this thread https://community.plone.org/t/does-anyone-have-any-suggestions-of-bringing-saveddata-count-to-another-part-of-a-plone-site-using-collective-easyform/7066/6 we discussed the difficulty of getting access to a form's save data (e.g. just to get a count of how many saved items).

I propose to add a new view @@get_save_data_adapters that returns a form's save data adapters. 

That way, a simple TAL expression can be used to get all of a form's saved data, including (in the simplest case) a count of the saved items.

**Comment by tomgross** [comment]
Can we document the usage of the view (https://github.com/collective/collective.easyform/blob/master/docs/actions.rst) before closing this issue?

**Comment by tkimnguyen** [comment]
fixed and merged!
