### ISSUE TITLE
Would be nice to have a radio button field other than just yes/no

### ISSUE THREAD

**Issue by RobZoneNet** [collective/collective.easyform#123]
I can't seem to find any radio button field options other than yes/no. I guess another place to have this is in choice. I am attaching a screen shot with choice field chosen. 
![screen shot 2018-08-24 at 8 51 12 am](https://user-images.githubusercontent.com/103745/44585628-fef33300-a77a-11e8-9a77-786df42b17fe.png)

**Comment by jensens** [comment]
![Screenshot at 2019-04-11 18-21-40](https://user-images.githubusercontent.com/157140/55973880-b1cebd80-5c86-11e9-91cb-67a926101f33.png)

seem in in 5.2 with latest release this works now.

**Comment by petschki** [comment]
As statet "others than yes/no" is not available ... if you make a simple choice you should be able to switch between select/radio and a multichoice should be able to switch between multiselect and checkbox ... right now you have to edit the XML schema by hand ... related: #134

**Comment by jensens** [comment]
Ok, got it wrong.
