### ISSUE TITLE
No support for checkboxes in V2

### ISSUE THREAD

**Issue by zopyx** [collective/collective.easyform#134]
collective.easyform support a multiple choice field which is rendered as multi select element but there is no way to render it as a set of checkboxes. The only workaround right now is to inject 

```
<form:widget type="z3c.form.browser.checkbox.CheckBoxFieldWidget"/>
```

directly into the XML model.

**Comment by agitator** [comment]
merged https://github.com/collective/collective.easyform/pull/149
