### ISSUE TITLE
Yes/No field with SingleCheckBoxBoolFieldWidget on Thanks-Page

### ISSUE THREAD

**Issue by krissik** [collective/collective.easyform#160]
If I have a Yes/No field with SingleCheckBoxBoolFieldWidget
![singlecheckboxboolfieldwidget](https://user-images.githubusercontent.com/5301889/57372296-7c3dc700-7195-11e9-912d-eaf2f3be71a3.jpg)

and I submit data
![doubled_yes_no_form](https://user-images.githubusercontent.com/5301889/57372308-89f34c80-7195-11e9-9cf6-df421d2c68e7.jpg)

the field name is doubled on thanks page
![doubled_yes_no_thankspage](https://user-images.githubusercontent.com/5301889/57372311-8d86d380-7195-11e9-9198-21d8ffb29ec2.jpg)

**Comment by jensens** [comment]
Tested, meanwhile this works with latest on Plone 5.2.2.
