### ISSUE TITLE
Planned new release?

### ISSUE THREAD

**Issue by krissik** [collective/collective.easyform#183]
Is a new release planned in near future? I am waiting for it because we need default values on fields in fieldsets (c85584dd588897822b69fd1daa16d0e53b3d6019)

Or is it worth to install from source?

**Comment by zopyx** [comment]
I also need a new release due the validation issues.

**Comment by tkimnguyen** [comment]
I'll try to get a release out shortly

**Comment by tkimnguyen** [comment]
2.1.1 is now on PyPI
