### ISSUE TITLE
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration (when modifying the supermodel XML manually)

### ISSUE THREAD

**Issue by zopyx** [collective/collective.easyform#216]
collective.easyform master:

- create a new EasyForm instance and visit the field editor (XML editor)
- the XML supermodel starts with the `<model>`  tag without XML preamble
- make a modification to the XML and save
- the XML shows up after SAVE with XML premable

Subsequent SAVE operations fail with 

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module collective.easyform.browser.fields, line 162, in __call__
  Module lxml.etree, line 3236, in lxml.etree.fromstring
  Module lxml.etree, line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

```

because the `source` form parameter is a `str` (in this case containing the XML preamble which can not be parsed with lxml. Only a UTF-8 encoded byte string can be parsed as XML with a XML preamble.

**Comment by mauritsvanrees** [comment]
This works fine now on master (4.1.2) with Plone 6.0.0.
