### ISSUE TITLE
folder_contents link in toolbar in the context of an EasyForm fields or mailer view is broker, normal view icon is not present

### ISSUE THREAD

**Issue by zopyx** [collective/collective.easyform#219]
- create a new EasyForm instance
- the toolbar will show the "Contents" option
- the "Contents" is linked to the parent object

Both makes no sense since an EF instance is not a folder and showing "Contents" for the parent object also makes no sense.

**Comment by fredvd** [comment]
To update this issue, there are some more toolbar issues: (Plone 5.2/Python3, easyform 3.0.2)

* When you edit fields or the mailers, the 'context' will become that view, and the Content's icon in the toolbar will link to <easyform_context>/folder_contents, causing an error.

* When you edit fields or the mailers: There is no way to get back to the easyform 'view', the view icon is missing. The only work around at the moment is to us the path bar. 

I don't think the folder contens icon being present is a big issue @zopyx , as we have the same for Pages. It allows you to go to the folder in which your item is stored. But the link is broken now when editing fields/mailers

**Comment by mauritsvanrees** [comment]
When you are at `plone/some-form/fields` you are at the `EasyFormFieldsView`.  This sounds like a standard browser view, and is registered as such, but it inherits from `plone.schemaeditor.browser.schema.traversal.SchemaContext`, which in turn inherits from `OFS.SimpleItem`. So it is not real, persistent content, but it acts a bit like it.

The url of the Contents action comes from this expression in standard Plone:

    string:${globals_view/getCurrentFolderUrl}/folder_contents

`getCurrentFolderUrl` basically calls `context/@@plone_context_state/folder` and gets the absolute url from there.  The `context` here is the fields view, which is not a folder. So the plone context state returns its parent folder: the easyform. So the Contents url is wrong.
Can't blame the plone context state for that.

In PR #239 Jens fixed a few action urls, but those are only for actions that are specific for easyform. (A test broke after that, but that probably needs a change in the test.)
Theoretically easyform could change the url of the Contents action, but I don't like that.

Easiest is probably: register a `folder_contents` view for easyform that redirects to the folder contents parent.

I have not yet looked at what happens with the View action and icon.

**Comment by fredvd** [comment]
Fixed in collective.easyform 3.0.3
