### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by reinhardt** [collective/collective.easyform#234]
We need a release of @thet's recent changes, but he's away this week. Could someone else please cut a new release or grant me permission to do so on PyPI? Maybe @jensens ?
Cheers!

**Comment by jensens** [comment]
3.0.0 is out - @reinhardt - may you please check if that worked? It is my first release with towncrier involved.

**Comment by reinhardt** [comment]
Change log is looking good, buildout is working - looks like a success! Thank you so much!
