### ISSUE TITLE
Datasaver does not persist data correctly.

### ISSUE THREAD

**Issue by adrianschulz** [collective/collective.easyform#259]
Some weeks ago we noticed data is missing in data savers of some of our EasyForms. After a lot of investigation we are now pretty sure there are problems with persisting the submitted data in some cases. See the following steps to reproduce with collective.easyform 3.0.6:

**Preparation**
- Run buildout & start instance
- Install the easy form-package

**Steps to reproduce**
- Add an EasyForm
- Adjust mailer so it does not throw errors when submitting data
- Add data saver (data saver 1) to Easyform
- Submit form as user (user data 1) -> user data 1 is stored in data saver 1 ✅ 
- Restart instance -> user data 1 is still stored in data saver 1 ✅ 
- Add second data saver (data saver 2) to easy form
- Submit form as user (user data 2) -> user data 2 is in both data savers. Userdata 1 is obviously only in data saver 1. ✅ 
- Restart instance -> data saver 2 is empty! Data saver 1 stores user data 1 & 2. ❌ 

**Further investigation**
- Remove mailer
- Submit form as user (user data 3) -> user data 3 is in both data savers. Userdata 1 & 2 only in data saver 1. ✅ 
- Restart instance -> user data 3 is In both data savers.  Userdata 1 & 2 only in data saver 1. ✅ 

We suppose there are some other paths to reproduce this because most of our EasyForms have only one data saver.

Currently, we have a workaround (see below) for our EasyForms but it’s not a proper long-term solution. So we would appreciate it If somebody with more know-how concerning persisting the data could have a look at it.

```
diff --git a/src/collective/easyform/actions.py b/src/collective/easyform/actions.py
index 0f82c9c..b16b3dc 100644
--- a/src/collective/easyform/actions.py
+++ b/src/collective/easyform/actions.py
@@ -608,7 +608,9 @@ class SaveData(Action):
             context._inputStorage = {}
         if self.__name__ not in context._inputStorage:
             context._inputStorage[self.__name__] = SavedDataBTree()
-        return context._inputStorage[self.__name__]
+            context._p_jar.add(context._inputStorage[self.__name__])
+            context._p_changed = True
+       return context._inputStorage[self.__name__]
 
     def clearSavedFormInput(self):
         # convenience method to clear input buffer
```

**Comment by maethu** [comment]
@adrianschulz Better late than never 😄, see #339 - This fixes your reported issue using PersistentMapping (which internally, does something similar what you proposed).
