### ISSUE TITLE
What is the use of authentication while adding new actions in easyforms ?

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#26]
While opening easyforms, when we click on ```actions``` button for a form, the browser url changes and it appends ```_authenticator=<Some token>``` . So I want to know if this is required here ? As it will be great if no changes will be there in url ?

**Comment by davilima6** [comment]
Yes, you need it. It's a new security system for Plone:

* http://pypi.python.org/pypi/plone.protect

You should generate it on the template:

* https://github.com/collective/cioppino.twothumbs/blob/master/cioppino/twothumbs/browser/templates/thumbs.pt#L19

Then grab it and use it in you Ajax posts: 

* https://github.com/collective/cioppino.twothumbs/blob/master/cioppino/twothumbs/browser/javascripts/twothumbs.js#L30-L32

**Comment by davilima6** [comment]
Btw this kind of question is more suitable in:

* http://stackoverflow.com/questions/tagged/plone
* https://community.plone.org/

**Comment by prakharjoshi** [comment]
Thanks :)
