### ISSUE TITLE
Plone 4 compatibility, on master or on a branch?

### ISSUE THREAD

**Issue by fredvd** [collective/collective.easyform#30]
With fixes for Plone 5 on the master branch, a broken CI-build and a separate Plone 5 branch it is unclear which versions are supported at the moment. 

Current master is not Plone 4 compatible anymore. 

* I've tried to work around the dependency on plone.schemaeditor to 2.0 >= by pinning to 2.0.7 exact because anything higher will break on the locales being removed and p.a.dexterity 2.0 wanting to import them and anything below will break on the plone.protect saga.  https://github.com/collective/collective.easyform/commit/b34201b460293ad06ad8dddecd8894ab0c884c75

* But even in the released 1.0a3 from last year link-overlay classes were removed in favor of pat-plone-modal which only works with patternslib/mockup patterns in Plone 5. this kils most models/adding fields, etc. https://github.com/collective/collective.easyform/commit/c1812e36f72bec970b50e0f435147eb417fd52bc

What's the best route to clean this up? Make a separate Plone4 branch from master and revert/fix what's necessary to create a workable Plone 4 branch again? And keep master in its current state before the plone 5 branch is merged back to master? @thet @kroman0 @davilima6

**Comment by davilima6** [comment]
+1 for the proposed path. Ideally master should remain on Plone 4 but since that might cause more harm than good (mainly for the existing plone 5 branches) and a merge is expected soon, I think a plone4 branch will do just fine.

Other important opinions: @smcmahon @prakharjoshi

**Comment by tomgross** [comment]
+1 for the proposition. @davilima6 @fredvd

**Comment by thet** [comment]
+1 for a Plone 4 specific branch and Plone 5 on master.

**Comment by tomgross** [comment]
Does anyone take care of this? The situation at the moment is confusing with several active feature/bugfix? branches.

**Comment by davilima6** [comment]
It's a [paused wip](https://community.plone.org/t/gsoc16-collective-easyform-development/1679/5). Atm newest branch is: [update-toolbar-items-for-easyforms](https://github.com/collective/collective.easyform/tree/).

**Comment by davilima6** [comment]
I made a PR (#35) so we get one less branch.

**Comment by jensens** [comment]
master is easyform 2 for plone5, 1.x is for plone 4

**Comment by thet** [comment]
I actually use the current master branch on a 4.3 project. But that's just to be said. The usability is worse, since the modal dialogues do not work very well.
