### ISSUE TITLE
No "add new fields" in field editor

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.easyform#315]
Plone 6 does not show the add fields button.  Unclear why.

**Comment by Rudd-O** [comment]
I'm using latest PyPI release of C.E.

**Comment by Rudd-O** [comment]
![Screenshot_20211226_035800](https://user-images.githubusercontent.com/346306/147398521-4d047418-857c-41b1-a29c-29db95dd3fd8.png)

**Comment by Rudd-O** [comment]
I see Plone 6 branch has the buttons.

**Comment by tkimnguyen** [comment]
Are those add choices not in the Actions menu?

**Comment by Rudd-O** [comment]
Nope.  They appear onscreen in the plone6 branch but not on master.

**Comment by laulaz** [comment]
Fixed now 👍
