### ISSUE TITLE
Forms always have id="form" and miss a name attribute,  necessary for form analytics by for example Matomo

### ISSUE THREAD

**Issue by fredvd** [collective/collective.easyform#325]
This issue is related to #324  . We are helping a customer with advanced form Analytics using Matomo. (It's a premium plugin though).  Matomo automatically detects forms on pages and tracks conversion.  This GDPR compatible because  personal data (the form contents) if never linked or associated, it only detects forms on url and then collects aggregate conversion  (form viewed, started filling in, submitted but form failure, real submission.

Matomo has the detection process documentation: 
* https://developer.matomo.org/guides/form-analytics/setup
* https://developer.matomo.org/guides/form-analytics/faq

the problem is: every easyform has id form and misses a name attribute. 

The culprit skeleton is nowhere in collective.easyform but in plone.app.z3cform's macros.pt that creates the z3c.form.Form easyform instantiates.  

* What should/could be added here is in the `tal:attributes` a name that requests `view/form_name`. 

* The interesting thing is that the macro in the tal:define already requests `view/form_name` but it is not defined on the EasyFormForm class. If we add it there as well and return self.context.Title() we're almost done.

However, this macros.pt is a very very generic wrapper around almost all forms in Plone...  What are the possible risks here by extending tal:attributes with a `name  view/form_name|context/title_or_id|nothing;`? 

cc: @mauritsvanrees

**Comment by mauritsvanrees** [comment]
Should be safe to add the `name` attribute to the form. It could be that a few robot or testbrowser tests fail. I can try.

A `name="This is a form title with spaces"` does not sound the best though. Maybe just take the id?

**Comment by mauritsvanrees** [comment]
I have created `plone.app.z3cform` PRs for [6.0](https://github.com/plone/plone.app.z3cform/pull/144) and [5.2](https://github.com/plone/plone.app.z3cform/pull/145).
