### ISSUE TITLE
EasyForm lacks an uninstall profile

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#36]
I added a controlpanel config for easyforms and I can see the config icon for easyform in controlpanel but when I uninstall the add on still the config icon for easyform is still there but it should not be there, right ?

Here is the part of code that implemented the config icon for control panel https://github.com/collective/collective.easyform/blob/add-controlpanel-config-for-easyforms/collective/easyform/profiles/default/controlpanel.xml . This is just a basic implementation of the config. I will improve that but my question is that it should be removed when the the add-on is uninstalled. I have tried that in incognito too so its not because of cached data. I will like to know if I am doing it right or not ?

**Comment by davilima6** [comment]
EasyForm currently lacks an uninstall profile. That's basic a copy of all files in profiles/default to profiles/uninstall, changing their contents to include `remove="True"`. See http://docs.plone.org/develop/addons/components/genericsetup.html#uninstall-profile

**Comment by prakharjoshi** [comment]
Thanks for pointing that out. I will create uninstall profile too.

**Comment by tomgross** [comment]
Hi @prakhar the easiest way to create an uninstall profile is to create a
package skeleton with bobtemplates.plone and copy over the relevant parts
to the original product.
prakhar <notifications@github.com> schrieb am Sa., 16. Juli 2016 um 13:27:

**Comment by prakharjoshi** [comment]
@tomgross @davilima6  Here are the changes for uninstalling the profile https://github.com/collective/collective.easyform/commit/ae4354aa6219a1a13e6096d91140a9aa9d16e50b . I followed the kewl blog and also the way suggested by Tom to create uninstall profile similar to bobtemplate.plone but its now working as of now. Correct me if I am going wrong at some place.

**Comment by davilima6** [comment]
@prakharjoshi You got almost everything right. I left a few comments where some fixes are required.

**Comment by prakharjoshi** [comment]
@davilima6  @pbauer  Thanks for suggestions. It worked finally !!

**Comment by prakharjoshi** [comment]
I guess uninstall profile is there is master. Changes are merged we can close this issue. Ideas ? @pbauer @davilima6 @tomgross

**Comment by tomgross** [comment]
@prakharjoshi Thanks!
