### ISSUE TITLE
Quotes in validators break the xml schema-editor with XMLSyntaxError

### ISSUE THREAD

**Issue by pbauer** [collective/collective.easyform#366]
When I add a simple validator to a field in python with quotes:

```
python: "quote" == True
```

The validator works but when I then open, edit and save the xml-Schema (using `fields/@@modeleditor`) the xml is invalid and cannot be saved because the double quotes in the validator close the ones in the xml-schema:

```xml
<model xmlns:i18n="http://xml.zope.org/namespaces/i18n" xmlns:marshal="http://namespaces.plone.org/supermodel/marshal" xmlns:form="http://namespaces.plone.org/supermodel/form" xmlns:security="http://namespaces.plone.org/supermodel/security" xmlns:indexer="http://namespaces.plone.org/supermodel/indexer" xmlns:lingua="http://namespaces.plone.org/supermodel/lingua" xmlns:users="http://namespaces.plone.org/supermodel/users" xmlns:easyform="http://namespaces.plone.org/supermodel/easyform" xmlns="http://namespaces.plone.org/supermodel/schema">
  <schema>
    <field name="smailnr" type="zope.schema.TextLine" easyform:TValidator="python: "quote" == True" easyform:serverSide="False" easyform:THidden="False">
      <description/>
      <required>False</required>
      <title>Test</title>
    </field>
  </schema>
</model>
```

That leads to 

`XMLSyntaxError: attributes construct error, line 3, column 85`

Single quotes work obviously.

**Comment by fredvd** [comment]
Confirmed. The cause or one of the causes is that the ACE editor has been replaced in Plone 6 with pat-code-editor. But that pattern wants escaped html in the textarea on which the pattern instantiates, and we didn't do that.  I experimented with  html.escape and html.unescape in the modeleditor view and I can get the editor to 'load' properly, but when trying to save the contents there's more dragons with escaping and the encodings where also html.unescape stumbles over what comes back from the browser. 

cc: @mauritsvanrees

**Comment by mauritsvanrees** [comment]
With current easyform 4.1.2 (I released this yesterday) and latest Plone 6, this works.
In the XML editor it now looks something like this:

    easyform:TValidator="python: &quot;hello&quot; == True" 

I don't know what such a validator would do, but I guess it was just an example for showing the quoting problem.
