### ISSUE TITLE
collective.easyform >= 4.1.0 Causing Plone Build Error

### ISSUE THREAD

**Issue by FarooqAlaulddin** [collective/collective.easyform#377]
I am having a problem while installing the new version of collective.easyform ( 4.1.0 and 4.1.1 ).
I am using: Plone 5.2.10 -- Python 3.8.12
 
    Installing client1.
        Version and requirements information containing plone.schemaeditor:
        [versions] constraint on plone.schemaeditor: 3.0.3
        Requirement of collective.easyform: plone.schemaeditor>=4.0.0b1
    While:
        Installing client1.
        Error: The requirement ('plone.schemaeditor>=4.0.0b1') is not allowed by your [versions] constraint (3.0.3)
        /opt/...

I tried pinpoint version plone.schemaeditor but it caused other dependency problems. I am able to work with collective.easyform 4.0.0
I wanted to see if anyone else is having the same issue?

**Comment by wesleybl** [comment]
Version 4.x of `collective.easyform` is for Plone 6 only. See:

https://github.com/collective/collective.easyform#compatibility

In Plone 5.2, you must use version 3.x.
