### ISSUE TITLE
Retrieving Saved Data using api in JSON form

### ISSUE THREAD

**Issue by yang242j** [collective/collective.easyform#406]
I am new to easyform. My team are trying to collect data using easy form. And one problem is that, we have so many forms which makes  manual data download impossible. So we are trying to seek a method to collect form data using api. 
Question is, is there a way to collect form data in JSON form through python script? 
So far, our thinking is to use requests.get to retrieve form data. But we dont know which endpoint to use. 
Can someone give us a clear example? Thanks in advance.

**Comment by davisagli** [comment]
Easyform includes a serializer for plone.restapi which includes saved data (https://github.com/collective/collective.easyform/blob/master/src/collective/easyform/serializer.py)

If you have plone.restapi installed then it should just be a matter of getting the API URL for the form, e.g. if the form is loaded as HTML at https://mysite.com/my-form then get the API representation at https://mysite.com/++api++/my-form

**Comment by yang242j** [comment]
Thanks for the reply. 
Suppose our site is http://ip-address/Plone, and the data I want is at http://ip-address/Plone/my-form/actions/form-dataset/@@data. Then to get the API representation, all I have to do is sending get request to http://ip-address/Plone/++api++/my-form/actions/form-dataset/@@data, right?
But I got 404 on http://ip-address/Plone/++api++, why is that? And I am sure the plone.restapi is enabled in the site add-on settings.

**Comment by davisagli** [comment]
The subpath actions/form-dataset/@@data is not part of the REST API; it is part of the browser UI for editing the form. I think the form data should be available at http://ip-address/Plone/++api++/my-form -- but, this may depend on having new enough versions of Plone and easyform, and you didn't say what versions you are using.

**Comment by yang242j** [comment]
Maybe it is because of older version, I still having the 404 error. My versions are listed below.

Plone 5.2.9 (5217)
CMF 2.6.0
Zope 4.8.2
Python 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
PIL 6.2.2 (Pillow)
WSGI: On
Server: waitress 2.1.2
collective.easyform 3.2.0
plone.restapi 7.8.0

**Comment by yang242j** [comment]
It is because of older version, supporting ++api++ since Plone 6.0.1 and plone.restapi 8.35.0. Thank you for the help
