### ISSUE TITLE
changes to field order do not stick

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#44]
This is happening on a Plone 5.1a2 site with the quintagroup code, as well as with the collective repo's 2.0.0a1.dev0 and the coredev Plone buildout 5.0.6.dev0
 
In the /fields view if you drag fields around they appear to be moved but reload the page and you see the fields are back in their original order. The only way to move fields and have the change stick seems to be to use the XML editor.

I tested this by creating a new form then adding a text field. That new field gets added to the bottom of the form. When I try to drag it to be anywhere else, the change does not stick.

**Comment by tmassman** [comment]
Just curious, I still can't reorder fields using the master branch.
