### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pbauer** [collective/collective.easyform#46]
Can we have a new release, please? I know it is not 100% done but I use it in production on several Plone 5-Sites without any issues and the last release is more than a year ago. I think a version 2.0a1 is called for.

**Comment by prakharjoshi** [comment]
👍

**Comment by agitator** [comment]
I'd like to see https://github.com/collective/collective.easyform/issues/13 fixed before.
Don't you have that issue?

**Comment by agitator** [comment]
what about https://github.com/collective/collective.easyform/issues/45 ?

**Comment by pbauer** [comment]
These issues are no blockers for a alpha-release or even for a beta.

**Comment by thet** [comment]
#45 maybe - because it would change how the settings are stored

**Comment by jensens** [comment]
#45 at least would need an migration step in a beta series
If we release alpha right now we can ignore migration later.
So I'am fine with an alpha release. Will do now (Frankfurt Airport is a boring place...).

**Comment by jensens** [comment]
ok, 2 alpha 1 is out. if anyone uses it, keep in mind that configuration might change and field order may be scrambled.
