### ISSUE TITLE
Multiple BCC recepients are not working

### ISSUE THREAD

**Issue by agitator** [collective/collective.easyform#49]
One would expect that multiple BCC recepients (one per line) would generate multiple BCC mails.
Right now only the first one is processed correctly and the following are just display above the normal mail content.

This probably the same for CC recepients

**Comment by tomgross** [comment]
@agitator Did you try a comma separated values?

**Comment by tomgross** [comment]
@agitator Does this PR fix your issue? https://github.com/collective/collective.easyform/pull/53

**Comment by agitator** [comment]
Thanx for the fix
