### ISSUE TITLE
Fields are only added to first fieldset in edit mode

### ISSUE THREAD

**Issue by tomgross** [collective/collective.easyform#50]
Steps to reproduce:
1. create an easyform
2. add a fieldset (switch to it, which is done automatically)
3. add a field -> it is added to the first fieldset but I'd expect it to be added to the current one

Very ugly workaround: Edit Form in XML and move the field to the new fieldset.

**Comment by agitator** [comment]
fixed with https://github.com/plone/plone.schemaeditor/commit/9ca407a140ada8f52423135dcd7ea71c162e1e32
