### ISSUE TITLE
Line breaks are not kept for body_pre, body_past, body_footer in mailer action

### ISSUE THREAD

**Issue by agitator** [collective/collective.easyform#56]

**Comment by prakharjoshi** [comment]
@agitator We add body_pre, body_post and body_footer through the editor when we create the form, right ? So I didn't get the line breaks part of the issue ?

**Comment by agitator** [comment]
these are fields within the mailer

i'm updating that to Richtext and TextAreaWidget with default_mime_type='text/x-web-intelligent'
