### ISSUE TITLE
included buildout.cfg in the easyform package no longer works

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#6]
There are 2 pinning/dependeny problems

docutils is easy to fix from 0.9.1 to 0.10, but (I think) the [sphinxbuilder] section is complaining about Pygments 2.0.2 cauing a version conflict:

While:
Installing sphinxbuilder.
Error: There is a version conflict.
We already have: Pygments 2.0.2

**Comment by tomgross** [comment]
This is probably a problem of virtualenv. In a fresh virtualenv the buildout works for me.

**Comment by prakharjoshi** [comment]
Yeah closing it for now.
