### ISSUE TITLE
Value of Boolean field is not displayed on thank you page

### ISSUE THREAD

**Issue by agitator** [collective/collective.easyform#62]
![screen shot 2017-03-06 at 14 53 33](https://cloud.githubusercontent.com/assets/365761/23612764/f2718bbc-027c-11e7-92b2-c668872d841d.png)

![screen shot 2017-03-06 at 14 53 10](https://cloud.githubusercontent.com/assets/365761/23612766/f4ef26b0-027c-11e7-8400-2c29eea7f5b4.png)

I tried to find my way to the origin of the problem but wasn't very successful.
Anyone with z3c.form experience that can give some pointers why this happens?

**Comment by agitator** [comment]
@datakurre @vangheem @tomgross have you got any pointers?

**Comment by datakurre** [comment]
@agitator It's that "Boolean description". If you select No, that description would be hidden. For alternative behavior you should register your own display widget for boolean fields on easyform.

**Comment by agitator** [comment]
works now
