### ISSUE TITLE
Thanks page needs some love

### ISSUE THREAD

**Issue by tomgross** [collective/collective.easyform#64]
- [ ] The thanks page should have a own URL .../form/thank-you to allow tracking successful submit with analytics software
- [ ] The help descriptions should NOT be visible on the thanks page
- [ ] The thanks page should NOT contain a form element. This is likely to break custom layouts which bind CSS on form elements. There is no form on the thanks page.

**Comment by agitator** [comment]
fixed with https://github.com/collective/collective.easyform/pull/65
