### ISSUE TITLE
Make content selection in HTMLabel work

### ISSUE THREAD

**Issue by tomgross** [collective/collective.easyform#67]
Collective.easyform provides a HTMLLabel field. This is useful für Hints about the terms of services with an internal link to a PDF.

Unfortunately the content selection in TinyMCE is broken for the HTMLlabel widget. It is impossible to link an internal object or image.

Seen on latest collective.easyform (40cdb45845e73745fdfaff1ed083a12f791663cb)

**Comment by agitator** [comment]
This is about the field "RichLabel" right?
And this is the error you're talking about?

![screen shot 2017-03-30 at 15 06 22](https://cloud.githubusercontent.com/assets/365761/24505599/bf069ff6-155a-11e7-9735-d38a82acd068.png)

**Comment by tomgross** [comment]
@agitator yes it is.
