### ISSUE TITLE
Extract Recipient and  reply-to from does not work

### ISSUE THREAD

**Issue by espenmn** [collective/collective.easyform#68]
Plone 5.1
Easyform checkout: '2.0.0a3.dev0

Overriding the reply to and / or recipient does not work 

![skjermbilde 2017-04-24 kl 09 42 48](https://cloud.githubusercontent.com/assets/1069235/25327027/dd3caf70-28d2-11e7-8797-dd9448243172.png)

**Comment by mauritsvanrees** [comment]
Works fine currently when I test it on master.  (Also on 1.x) I guess it has been fixed somewhere in the past two years.
Please reopen if you still have this problem.
