### ISSUE TITLE
remove alpha status

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#72]
@svx and I are arguing :) in https://github.com/plone/documentation/issues/711#issuecomment-303818618 

Can we release this as non-alpha now? Many of us are using this as is and as far as I know it's fine.

@gforcada @tomgross @agitator @jensens

**Comment by tomgross** [comment]
I have mixed feelings about changing from alpha. There is still a lot to do on polishing and you can shoot you in the foot if you go off the beaten track. I'd wait for the next Plone release which contains a fix for #50. #67 should also be fixed soon.  The thanks page also needs some more love #62 

+1 for a release but I'd still go for alpha

A sprint would be good ...

**Comment by tkimnguyen** [comment]
The problem with waiting and not having some idea of the production release timeframe is what it represents for Plone 5: the continuing saga, now almost 2 years old, of not having important add-ons upgraded to match Plone 5. :(

**Comment by jensens** [comment]
But Tom is right, there is work todo until we can make it final. Probably beta is possible.

**Comment by agitator** [comment]
last one before beta https://github.com/collective/collective.easyform/issues/62
@jensens @tomgross what was the state on this?

**Comment by jensens** [comment]
IMO first plone/plone.app.z3cform#65 need to be finished and merged, then #62 can be addressed.

**Comment by agitator** [comment]
https://pypi.python.org/pypi/collective.easyform/2.0.0b1 is released

**Comment by jensens** [comment]
which implies easyform 2.x is now a Plone 5.1 thing

**Comment by agitator** [comment]
@tkimnguyen shall I change the classifiers to 5.1 only (for the next release)?

**Comment by tkimnguyen** [comment]
I am not sure I follow why 2.x is now only for Plone 5.1, but if that's indeed the case then yeah the classifier should reflect that. (sorry for delay)
