### ISSUE TITLE
New fields are always added to the "default" fieldset instead to the current fieldset

### ISSUE THREAD

**Issue by zopyx** [collective/collective.easyform#73]
Plone 5.1, collective.easyform2.0.0a..

Creating a new field within the context of a fieldset has the effect that the field is alway added to the default fieldset instead of to the current fieldset.

**Comment by thet** [comment]
Duplicate of https://github.com/collective/collective.easyform/issues/50 and fixed here: https://github.com/plone/plone.schemaeditor/pull/54

This was actually a problem with plone.schemaeditor and also broken for the Dexterity schema editing form.

**Comment by zopyx** [comment]
The error is persistent in at least the latested plone.schemaeditor 2.0.17 release

**Comment by tomgross** [comment]
A recent mockup is needed too. AFAIK there is no release yet.
