### ISSUE TITLE
Use contents of "thanks" page in confirmation mail

### ISSUE THREAD

**Issue by thet** [collective/collective.easyform#76]
- Add an option to use contents of "thanks" page in confirmation mail.

**Comment by tomgross** [comment]
The content of the thanks email needs to be fixed generally. For the thanks page the z3c.form display widgets are used but for the e-mail the plain values. Which leads to ugly `set([...])` entries for multiple choice fields.

**Comment by tomgross** [comment]
```
From: ...
To: ...
From nobody Tue Sep 12 12:09:43 2017
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
To: ...
From: ...
Subject: =?utf-8?q?Form_Submission?=
X-HTTP_X_FORWARDED_FOR: 
X-REMOTE_ADDR: 127.0.0.1
X-PATH_INFO: /Plone/a-form
Date: Tue, 12 Sep 2017 12:09:43 +0200

<html xmlns=3D"http://www.w3.org/1999/xhtml">
  <head><title></title></head>
  <body>
    <p></p>
    <dl>
        =

            <dt>Multi</dt>
            <dd>set([u'Orange', u'Apple'])</dd>
        =

    </dl>
    <p></p>
    <p></p>
  </body>
</html>

```

**Comment by tomgross** [comment]
The same is true for CSV save adapter:

```
"set([u'Orange', u'Pear'])"
"set([u'Orange', u'Apple'])"
```

**Comment by tomgross** [comment]
Another issue/use-case is: The thanks-page/email should respect the localized date(time) format.

**Comment by tomgross** [comment]
With https://github.com/collective/collective.easyform/blob/master/src/collective/easyform/actions.py#L226 it is now possible to access the rendered display widget in the confirmation e-mail.

@thet What do you think? Does this solve your issue?

**Comment by tomgross** [comment]
The situation here has improved. I'm closing this. @thet please reopen if you disagree.
