### ISSUE TITLE
version conflict with plone.schemaeditor when running buildout

### ISSUE THREAD

**Issue by VicenteIranzoMaestre** [collective/collective.easyform#93]
On a recent commit ([bd91d6c02a9ddd8259548aee0a5787234a827acf](https://github.com/collective/collective.easyform/commit/bd91d6c02a9ddd8259548aee0a5787234a827acf)) the required version of plone.schemaeditor was fixed to 2.0.18. 

This version is higher than the version required in the versions.cfg of all the actual plone(which is 2.0.17). When running buildout it fails because of this.

Is there any reason for this?
Is it safe to pass over the fixed versions by plone?

Thank you very much,

Vicente Iranzo Maestre

**Comment by tomgross** [comment]
While it _might_ work on Plone 5.0.x collective.easyform 2.x is generally targeted at Plone 5.1.x onwards. If you use it with Plone 5.0.x you have to pin the dependencies (like plone.schemaeditor) to the requested versions.
