### ISSUE TITLE
"possible values" field for multi select form fields is empty on edit

### ISSUE THREAD

**Issue by petschki** [collective/collective.easyform#96]
I tried to edit/delete possible values for multiselection field but the previously defined values are gone.

**Comment by tomgross** [comment]
@petschki does https://github.com/plone/plone.schemaeditor/pull/57 fix your issue?

**Comment by petschki** [comment]
@tomgross yes, this fixes the issue. just tried out https://github.com/plone/plone.schemaeditor/pull/57 and the previously defined values are back.

**Comment by jensens** [comment]
this was merged.
